#批量添加和修改、删除front matter配置文件

# 需要批量处理的路径，docs文件夹内的文件夹
path:
  - 00.目录页
  - 01.前端
  - 02.架构
  - 03.更多
  - 04.关于
  - 05.收藏夹

# 要删除的字段 (数组)
delete:
  # - tags

 # 要添加、修改front matter的数据 （front matter中没有的数据则添加，已有的数据则覆盖）
data:
  date: 2021-12-21 21:50:53
  author:
    name: webxmsj
    link: https://github.com/webxmsj
